<template><h1 id="spring-cloud-stream-消息驱动-消费异常处理机制" tabindex="-1"><a class="header-anchor" href="#spring-cloud-stream-消息驱动-消费异常处理机制" aria-hidden="true">#</a> Spring Cloud Stream 消息驱动-消费异常处理机制</h1>
<p>在 Spring Cloud Stream 中，提供了通用的消费异常处理机制，可以拦截到消费者消费消息时发生的异常，进行自定义的处理逻辑。</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code>  <span class="token comment">/*针对于单个通道和分组的监听*/</span>
    <span class="token annotation punctuation">@ServiceActivator</span><span class="token punctuation">(</span>inputChannel <span class="token operator">=</span> <span class="token string">"&lt;destination>.&lt;group>.errors"</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">handleError</span><span class="token punctuation">(</span><span class="token class-name">ErrorMessage</span> errorMessage<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">"[handleError][payload：{}]"</span><span class="token punctuation">,</span> <span class="token class-name">ExceptionUtils</span><span class="token punctuation">.</span><span class="token function">getRootCauseMessage</span><span class="token punctuation">(</span>errorMessage<span class="token punctuation">.</span><span class="token function">getPayload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">"[handleError][originalMessage：{}]"</span><span class="token punctuation">,</span> errorMessage<span class="token punctuation">.</span><span class="token function">getOriginalMessage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">"[handleError][headers：{}]"</span><span class="token punctuation">,</span> errorMessage<span class="token punctuation">.</span><span class="token function">getHeaders</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token comment">/*全局的错误监听*/</span>
    <span class="token annotation punctuation">@StreamListener</span><span class="token punctuation">(</span><span class="token class-name">IntegrationContextUtils</span><span class="token punctuation">.</span>ERROR_CHANNEL_BEAN_NAME<span class="token punctuation">)</span> <span class="token comment">// errorChannel</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">globalHandleError</span><span class="token punctuation">(</span><span class="token class-name">ErrorMessage</span> errorMessage<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">"[globalHandleError][payload：{}]"</span><span class="token punctuation">,</span> <span class="token class-name">ExceptionUtils</span><span class="token punctuation">.</span><span class="token function">getRootCauseMessage</span><span class="token punctuation">(</span>errorMessage<span class="token punctuation">.</span><span class="token function">getPayload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">"[globalHandleError][originalMessage：{}]"</span><span class="token punctuation">,</span> errorMessage<span class="token punctuation">.</span><span class="token function">getOriginalMessage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">"[globalHandleError][headers：{}]"</span><span class="token punctuation">,</span> errorMessage<span class="token punctuation">.</span><span class="token function">getHeaders</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div></template>
